require('dotenv').config();
const express = require('express');
const bodyParser = require('body-parser');
const nodemailer = require('nodemailer');

// --- Email Setup ---
let transporter;

if (process.env.SMTP_EMAIL && process.env.SMTP_EMAIL !== 'your-email@gmail.com') {
    transporter = nodemailer.createTransport({
        service: 'gmail',
        auth: {
            user: process.env.SMTP_EMAIL,
            pass: process.env.SMTP_PASSWORD
        }
    });
    console.log(`\n📧 [EMAIL SYSTEM READY] Using your configured Gmail account.`);
} else {
    // Fallback to Ethereal Testing Account if .env is not configured
    nodemailer.createTestAccount((err, account) => {
        if (err) {
            console.error('Failed to create a testing account. ' + err.message);
            return;
        }
        transporter = nodemailer.createTransport({
            host: account.smtp.host,
            port: account.smtp.port,
            secure: account.smtp.secure,
            auth: {
                user: account.user,
                pass: account.pass
            }
        });
        console.log(`\n📧 [EMAIL SYSTEM READY] Using Ethereal Mock Email (Fallback).`);
        console.log(`Please configure your .env file with real Gmail credentials to send actual emails.\n`);
    });
}

async function sendAdminEmail(employeeName, componentName) {
    if (!transporter) return;

    const htmlContent = `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; border: 1px solid #e2e8f0; border-radius: 8px; overflow: hidden; box-shadow: 0 4px 6px -1px rgba(0,0,0,0.05);">
            <div style="background-color: #0369a1; color: white; padding: 20px; text-align: center;">
                <h1 style="margin: 0; font-size: 24px; letter-spacing: 1px;">⚙️ SyncTrack</h1>
                <p style="margin: 5px 0 0 0; font-size: 14px; opacity: 0.9;">Intelligent Inventory Management System</p>
            </div>
            
            <div style="padding: 30px 20px;">
                <p style="margin-top: 0; font-size: 16px; color: #1e293b;">Dear <strong>System Administrator</strong>,</p>
                <p style="font-size: 15px; color: #475569; line-height: 1.6;">This is to inform you that a critical checkout request has been registered and requires your approval.</p>
                
                <table style="width: 100%; border-collapse: collapse; margin: 25px 0;">
                    <tr>
                        <td style="padding: 10px; border-bottom: 1px solid #e2e8f0; font-weight: bold; width: 40%; color: #475569;">Employee Name</td>
                        <td style="padding: 10px; border-bottom: 1px solid #e2e8f0; color: #1e293b;">${employeeName}</td>
                    </tr>
                    <tr>
                        <td style="padding: 10px; border-bottom: 1px solid #e2e8f0; font-weight: bold; color: #475569;">Component Requested</td>
                        <td style="padding: 10px; border-bottom: 1px solid #e2e8f0; color: #1e293b;">${componentName}</td>
                    </tr>
                    <tr>
                        <td style="padding: 10px; border-bottom: 1px solid #e2e8f0; font-weight: bold; color: #475569;">Request Status</td>
                        <td style="padding: 10px; border-bottom: 1px solid #e2e8f0; color: #ef4444; font-weight: bold;">CRITICAL (Pending Approval)</td>
                    </tr>
                </table>

                <p style="font-size: 14px; color: #64748b; margin-bottom: 15px;">Please log in to the Dashboard's Admin Approvals section to Accept or Reject this request.</p>
                
                <div style="text-align: center; margin-top: 30px; margin-bottom: 10px;">
                    <a href="http://localhost:3000" style="background-color: #0284c7; color: white; text-decoration: none; padding: 12px 24px; border-radius: 6px; font-weight: bold; display: inline-block;">Go to Dashboard</a>
                </div>
            </div>
            
            <div style="background-color: #f8fafc; padding: 15px 20px; text-align: center; border-top: 1px solid #e2e8f0;">
                <p style="margin: 0; font-size: 11px; color: #94a3b8;">This is an automated message generated by the SyncTrack Attendance System.</p>
            </div>
        </div>
    `;

    try {
        let info = await transporter.sendMail({
            from: '"SyncTrack Alerts" <alerts@synctrack.local>',
            to: 'teletracktest2@gmail.com',
            subject: "CRITICAL: Component Request Approval Required",
            html: htmlContent
        });
        console.log("=================================================");
        console.log("📨 Email dispatched for Admin Approval");
        console.log("🔗 Preview Email URL: %s", nodemailer.getTestMessageUrl(info));
        console.log("=================================================");
    } catch (err) {
        console.error("Email sending failed:", err);
    }
}
const cors = require('cors');
const WebSocket = require('ws');
const http = require('http');
const crypto = require('crypto');
const db = require('./db');
const path = require('path');

const app = express();
const server = http.createServer(app);
const wss = new WebSocket.Server({ server });

app.use(cors());
app.use(bodyParser.json());

const ROLE_LEVEL = {
    operator: 1,
    manager: 2,
    admin: 3
};

const activeSessions = new Map();

function normalizeRole(role) {
    const clean = String(role || '').toLowerCase();
    return ROLE_LEVEL[clean] ? clean : 'operator';
}

function issueToken(user) {
    const token = crypto.randomBytes(24).toString('hex');
    activeSessions.set(token, {
        username: user.username,
        role: normalizeRole(user.role),
        displayName: user.display_name || user.username,
        createdAt: Date.now()
    });
    return token;
}

function getClientIp(req) {
    return req.headers['x-forwarded-for'] || req.socket.remoteAddress || '';
}

function getAuthContext(req) {
    const authHeader = req.headers.authorization || '';
    const token = authHeader.startsWith('Bearer ') ? authHeader.slice(7) : req.headers['x-auth-token'];
    if (!token) {
        return null;
    }
    const session = activeSessions.get(token);
    if (!session) {
        return null;
    }
    return { ...session, token };
}

function requireRole(minRole, options = {}) {
    const required = normalizeRole(minRole);
    const allowPrototypeFallback = options.allowPrototypeFallback !== false;

    return (req, res, next) => {
        const auth = getAuthContext(req);
        req.auth = auth;

        if (!auth) {
            if (allowPrototypeFallback) {
                req.auth = {
                    username: 'prototype-admin',
                    role: 'admin',
                    displayName: 'Prototype Admin'
                };
                return next();
            }
            return res.status(401).json({ error: 'Authentication required' });
        }

        if (ROLE_LEVEL[auth.role] < ROLE_LEVEL[required]) {
            return res.status(403).json({ error: `Requires ${required} role or higher` });
        }

        return next();
    };
}

function writeAuditLog(entry) {
    const payload = {
        actor_username: entry.actorUsername || 'system',
        actor_role: normalizeRole(entry.actorRole || 'operator'),
        action: entry.action || 'unknown_action',
        entity_type: entry.entityType || null,
        entity_id: entry.entityId || null,
        status: entry.status || 'success',
        details: entry.details ? JSON.stringify(entry.details) : null,
        ip_address: entry.ipAddress || null
    };

    db.run(`INSERT INTO audit_logs
        (actor_username, actor_role, action, entity_type, entity_id, status, details, ip_address)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?)`, [
        payload.actor_username,
        payload.actor_role,
        payload.action,
        payload.entity_type,
        payload.entity_id,
        payload.status,
        payload.details,
        payload.ip_address
    ], (err) => {
        if (err) {
            console.error('Failed to write audit log:', err.message);
        }
    });
}

function auditFromRequest(req, event) {
    writeAuditLog({
        actorUsername: req.auth?.username || 'anonymous',
        actorRole: req.auth?.role || 'operator',
        ipAddress: getClientIp(req),
        ...event
    });
}

// Serve the dashboard statically
app.use(express.static(path.join(__dirname, '../dashboard'), { index: 'home.html' }));

// ==========================================
// ADMIN AUTHENTICATION
// ==========================================
app.post('/api/login', (req, res) => {
    const { username, password } = req.body;

    if (!username || !password) {
        return res.status(400).json({ error: 'Username and password are required' });
    }

    db.get(`SELECT username, password, role, display_name, is_active
            FROM users WHERE username = ?`, [username], (err, user) => {
        if (err) {
            return res.status(500).json({ error: 'Database error' });
        }

        if (!user || !user.is_active || user.password !== password) {
            writeAuditLog({
                actorUsername: username,
                actorRole: 'operator',
                action: 'auth.login',
                entityType: 'session',
                entityId: username,
                status: 'failed',
                details: { reason: 'invalid_credentials' },
                ipAddress: getClientIp(req)
            });
            return res.status(401).json({ error: 'Invalid credentials' });
        }

        const token = issueToken(user);

        writeAuditLog({
            actorUsername: user.username,
            actorRole: user.role,
            action: 'auth.login',
            entityType: 'session',
            entityId: token.slice(0, 12),
            status: 'success',
            details: { displayName: user.display_name || user.username },
            ipAddress: getClientIp(req)
        });

        return res.json({
            token,
            role: normalizeRole(user.role),
            username: user.username,
            displayName: user.display_name || user.username
        });
    });
});

app.get('/api/auth/me', requireRole('operator'), (req, res) => {
    res.json({
        username: req.auth.username,
        role: req.auth.role,
        displayName: req.auth.displayName || req.auth.username
    });
});

// ==========================================
// HARDWARE ENROLLMENT (From ESP32 Gate Reader)
// ==========================================
app.post('/api/enroll', (req, res) => {
    const { uid, type } = req.body;
    if (!uid || !type) return res.status(400).json({ error: "Missing uid or type" });

    if (type === 'employee') {
        db.run(`INSERT OR IGNORE INTO employees (uid, name) VALUES (?, ?)`,
            [uid, 'New Employee (Edit via Dashboard)'], function (err) {
                if (err) return res.status(500).json({ error: err.message });
                broadcastUpdate({ type: 'alert', message: `🆕 New Employee Card enrolled from Gate: ${uid}`, severity: 'info' });
                broadcastUpdate({ type: 'inventory_update' });
                res.status(201).json({ message: "Employee enrolled", uid });
            });
    } else if (type === 'component') {
        db.run(`INSERT OR IGNORE INTO components (uid, name, status) VALUES (?, ?, 'IN')`,
            [uid, 'New Component (Edit via Dashboard)'], function (err) {
                if (err) return res.status(500).json({ error: err.message });
                broadcastUpdate({ type: 'alert', message: `🆕 New Component Tag enrolled from Gate: ${uid}`, severity: 'info' });
                broadcastUpdate({ type: 'inventory_update' });
                res.status(201).json({ message: "Component enrolled", uid });
            });
    } else {
        res.status(400).json({ error: "Invalid type. Use 'employee' or 'component'." });
    }
});

// ==========================================
// WIFI CONFIG (OTA Provisioning for ESP32)
// ==========================================
let wifiProfiles = [];

function normalizeWifiProfiles(body) {
    if (Array.isArray(body.profiles)) {
        return body.profiles
            .map(profile => ({
                ssid: String(profile.ssid || '').trim(),
                password: String(profile.password || '')
            }))
            .filter(profile => profile.ssid.length > 0)
            .slice(0, 5);
    }

    const ssid = String(body.ssid || '').trim();
    if (!ssid) {
        return [];
    }

    return [{ ssid, password: String(body.password || '') }];
}

app.get('/api/wifi-config', (req, res) => {
    if (wifiProfiles.length === 0) {
        return res.status(404).json({ error: "No WiFi profiles set yet. Set them from the Dashboard." });
    }

    res.json({ profiles: wifiProfiles, count: wifiProfiles.length });
});

app.post('/api/wifi-config', requireRole('manager'), (req, res) => {
    const profiles = normalizeWifiProfiles(req.body || {});

    if (profiles.length === 0) {
        return res.status(400).json({ error: "At least one SSID is required" });
    }

    wifiProfiles = profiles;

    auditFromRequest(req, {
        action: 'wifi.update_profiles',
        entityType: 'wifi_config',
        entityId: 'global',
        details: { count: wifiProfiles.length }
    });

    broadcastUpdate({
        type: 'alert',
        message: `📡 WiFi profiles updated (${wifiProfiles.length}). Devices will fetch on next sync.`,
        severity: 'info'
    });

    broadcastUpdate({ type: 'wifi_config_updated', profiles: wifiProfiles, count: wifiProfiles.length });

    res.json({
        message: "WiFi profiles saved. ESP32 devices will pick them up automatically.",
        profiles: wifiProfiles,
        count: wifiProfiles.length
    });
});

// ==========================================
// CONFIG & STATE (In-Memory for simplicity)
// ==========================================
let geofenceConfig = {
    lat: 18.5204,
    lng: 73.8567,
    radius: 500, // meters
    name: "Authorized Work Zone"
};

const activeTrackers = {}; // State for GPS smoothing

// WebSocket connections
wss.on('connection', (ws) => {
    console.log('Dashboard client connected via WebSocket');
    ws.send(JSON.stringify({ type: 'status', message: 'Connected to Live Tracking' }));
    // Send current geofence config to new clients
    ws.send(JSON.stringify({ type: 'geofence_config', ...geofenceConfig }));
});

function broadcastUpdate(data) {
    wss.clients.forEach((client) => {
        if (client.readyState === WebSocket.OPEN) {
            client.send(JSON.stringify(data));
        }
    });
}

// ==========================================
// HELPER: Calculate distance between two GPS points (Haversine)
// ==========================================
function haversineDistance(lat1, lng1, lat2, lng2) {
    const R = 6371000; // Earth's radius in meters
    const dLat = (lat2 - lat1) * Math.PI / 180;
    const dLng = (lng2 - lng1) * Math.PI / 180;
    const a = Math.sin(dLat / 2) * Math.sin(dLat / 2) +
        Math.cos(lat1 * Math.PI / 180) * Math.cos(lat2 * Math.PI / 180) *
        Math.sin(dLng / 2) * Math.sin(dLng / 2);
    const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
    return R * c; // Distance in meters
}

// ==========================================
// API ROUTES
// ==========================================

// 1. RFID GATE SCANNER (Check in / Check out)
app.post('/api/transactions/scan', (req, res) => {
    let { componentUid, employeeUid } = req.body;

    if (!componentUid || !employeeUid) {
        return res.status(400).json({ error: "Missing UIDs" });
    }

    console.log(`Gate Scan Received: ID1=${componentUid}, ID2=${employeeUid}`);

    // ORDER AGNOSTIC LOOKUP (Find which is Component and which is Employee)
    db.get(`SELECT uid FROM components WHERE uid = ? OR uid = ?`, [componentUid, employeeUid], (err, compRow) => {
        if (err || !compRow) return res.status(404).json({ error: "No valid component tag scanned" });

        db.get(`SELECT uid FROM employees WHERE uid = ? OR uid = ?`, [componentUid, employeeUid], (err, empRow) => {
            if (err || !empRow) return res.status(404).json({ error: "No valid employee card scanned" });

            const realCompUid = compRow.uid;
            const realEmpUid = empRow.uid;

            db.get(`SELECT * FROM components WHERE uid = ?`, [realCompUid], (err, comp) => {
                db.get(`SELECT * FROM employees WHERE uid = ?`, [realEmpUid], (err, emp) => {

                    let isCheckingOut = comp.status === 'IN';
                    let newStatus = isCheckingOut ? 'OUT' : 'IN';
                    let assignedTo = isCheckingOut ? emp.name : null;

                    // --- AUTOMATIC CHECKOUT ---
                    // The employee scanned both tags, immediately check it out to them.
                    if (isCheckingOut) {
                        console.log(`✅ Automatic Checkout: ${emp.name} is taking ${comp.name}`);
                        broadcastUpdate({
                            type: 'alert',
                            message: `✅ Successful Check-out: ${emp.name} took ${comp.name}. GPS tracking started.`,
                            severity: 'info'
                        });
                    }

                    db.run(`UPDATE components SET status = ?, assigned_to = ?, approved_for_uid = NULL WHERE uid = ?`,
                        [newStatus, assignedTo, realCompUid], function (err) {
                            if (err) return res.status(500).json({ error: "Database error" });

                            db.run(`INSERT INTO transactions (component_uid, employee_uid, action) VALUES (?, ?, ?)`,
                                [realCompUid, realEmpUid, newStatus]);

                            broadcastUpdate({
                                type: 'inventory_update',
                                component: comp.name,
                                employee: emp.name,
                                action: newStatus
                            });

                            res.status(200).json({ message: `Successfully checked ${newStatus}` });
                        });
                });
            });
        });
    });
});

// 2. GPS TRACKER UPDATES (with geofence check)
app.post('/api/tracking', (req, res) => {
    const { trackerId, lat, lng } = req.body;

    if (!trackerId || !lat || !lng) {
        return res.status(400).json({ error: "Missing GPS data" });
    }

    console.log(`Raw GPS Update -> Tracker: ${trackerId} | Lat: ${lat}, Lng: ${lng}`);

    // --- EXPERIMENTAL: GPS PRECISION FILTER (EMA Smoothing) ---
    // The NEO-6M naturally jumps around. We apply an Exponential Moving Average
    // to smooth the path and make the map look highly precise.
    let finalLat = parseFloat(lat);
    let finalLng = parseFloat(lng);

    if (!activeTrackers[trackerId]) {
        activeTrackers[trackerId] = { lat: finalLat, lng: finalLng };
    } else {
        const alpha = 0.4; // Smoothing factor (lower = smoother but more lag)
        finalLat = (alpha * finalLat) + ((1 - alpha) * activeTrackers[trackerId].lat);
        finalLng = (alpha * finalLng) + ((1 - alpha) * activeTrackers[trackerId].lng);

        // Update state
        activeTrackers[trackerId].lat = finalLat;
        activeTrackers[trackerId].lng = finalLng;
    }

    console.log(`Smoothed GPS   -> Lat: ${finalLat.toFixed(6)}, Lng: ${finalLng.toFixed(6)}`);

    // Log to DB (using the smoothed coordinates for cleaner history)
    db.run(`INSERT INTO gps_logs (tracker_id, lat, lng) VALUES (?, ?, ?)`, [trackerId, finalLat, finalLng], (err) => {
        if (err) console.error("Could not save GPS log:", err);
    });

    // Calculate distance from geofence center using smoothed data
    const distFromZone = haversineDistance(finalLat, finalLng, geofenceConfig.lat, geofenceConfig.lng);
    const isOutsideGeofence = distFromZone > geofenceConfig.radius;

    if (isOutsideGeofence) {
        console.log(`⚠️ GEOFENCE ALERT: ${trackerId} is ${Math.round(distFromZone)}m from work zone!`);
    }

    broadcastUpdate({
        type: 'gps_update',
        trackerId,
        lat: finalLat,
        lng: finalLng,
        distanceFromZone: Math.round(distFromZone),
        isOutsideGeofence,
        timestamp: new Date().toISOString()
    });

    res.status(200).json({ message: "Location received", distanceFromZone: Math.round(distFromZone), isOutsideGeofence });
});

// 3. GET INVENTORY STATUS
app.get('/api/inventory', (req, res) => {
    db.all(`SELECT * FROM components`, [], (err, rows) => {
        if (err) return res.status(500).json({ error: err.message });
        res.json({ components: rows });
    });
});

// 3a. ADD COMPONENT
app.post('/api/components', requireRole('manager'), (req, res) => {
    const { uid, tracker_id, name } = req.body;
    if (!uid || !name) return res.status(400).json({ error: "Missing uid or name" });
    db.run(`INSERT INTO components (uid, tracker_id, name) VALUES (?, ?, ?)`, [uid, tracker_id || null, name], function (err) {
        if (err) return res.status(500).json({ error: err.message });
        auditFromRequest(req, {
            action: 'component.create',
            entityType: 'component',
            entityId: uid,
            details: { name, tracker_id: tracker_id || null }
        });
        broadcastUpdate({ type: 'inventory_update', action: 'component_added', component: name, componentUid: uid });
        res.status(201).json({ message: "Component added successfully" });
    });
});

// 3b. REMOVE COMPONENT
app.delete('/api/components/:uid', requireRole('manager'), (req, res) => {
    db.run(`DELETE FROM components WHERE uid = ?`, [req.params.uid], function (err) {
        if (err) return res.status(500).json({ error: err.message });
        auditFromRequest(req, {
            action: 'component.delete',
            entityType: 'component',
            entityId: req.params.uid
        });
        broadcastUpdate({ type: 'inventory_update', action: 'component_deleted', componentUid: req.params.uid });
        res.json({ message: "Component removed successfully" });
    });
});

// 4. GET EMPLOYEES
app.get('/api/employees', (req, res) => {
    db.all(`SELECT * FROM employees`, [], (err, rows) => {
        if (err) return res.status(500).json({ error: err.message });
        res.json({ employees: rows });
    });
});

// 4a. ADD EMPLOYEE
app.post('/api/employees', requireRole('manager'), (req, res) => {
    const { uid, name } = req.body;
    if (!uid || !name) return res.status(400).json({ error: "Missing uid or name" });
    db.run(`INSERT INTO employees (uid, name) VALUES (?, ?)`, [uid, name], function (err) {
        if (err) return res.status(500).json({ error: err.message });
        auditFromRequest(req, {
            action: 'employee.create',
            entityType: 'employee',
            entityId: uid,
            details: { name }
        });
        broadcastUpdate({ type: 'inventory_update', action: 'employee_added', employee: name, employeeUid: uid });
        res.status(201).json({ message: "Employee added successfully" });
    });
});

// 4b. REMOVE EMPLOYEE
app.delete('/api/employees/:uid', requireRole('manager'), (req, res) => {
    db.run(`DELETE FROM employees WHERE uid = ?`, [req.params.uid], function (err) {
        if (err) return res.status(500).json({ error: err.message });
        auditFromRequest(req, {
            action: 'employee.delete',
            entityType: 'employee',
            entityId: req.params.uid
        });
        broadcastUpdate({ type: 'inventory_update', action: 'employee_deleted', employeeUid: req.params.uid });
        res.json({ message: "Employee removed successfully" });
    });
});

// 5. GET GPS HISTORY (for trail and playback)
app.get('/api/tracking/history', (req, res) => {
    const { trackerId, date } = req.query;
    let query = `SELECT * FROM gps_logs`;
    let params = [];

    if (trackerId && date) {
        query += ` WHERE tracker_id = ? AND DATE(timestamp) = ?`;
        params = [trackerId, date];
    } else if (trackerId) {
        query += ` WHERE tracker_id = ?`;
        params = [trackerId];
    }

    query += ` ORDER BY timestamp ASC`;

    db.all(query, params, (err, rows) => {
        if (err) return res.status(500).json({ error: err.message });
        res.json({ locations: rows });
    });
});

// 6. GET / SET GEOFENCE CONFIG
app.get('/api/geofence', (req, res) => {
    res.json(geofenceConfig);
});

app.post('/api/geofence', requireRole('manager'), (req, res) => {
    const { lat, lng, radius, name } = req.body;
    if (lat) geofenceConfig.lat = lat;
    if (lng) geofenceConfig.lng = lng;
    if (radius) geofenceConfig.radius = radius;
    if (name) geofenceConfig.name = name;

    console.log(`Geofence updated: ${JSON.stringify(geofenceConfig)}`);

    auditFromRequest(req, {
        action: 'geofence.update',
        entityType: 'geofence',
        entityId: 'default_zone',
        details: geofenceConfig
    });

    broadcastUpdate({ type: 'geofence_config', ...geofenceConfig });
    res.json({ message: "Geofence updated", config: geofenceConfig });
});

// 7. GET TRANSACTION HISTORY
app.get('/api/transactions', (req, res) => {
    const { date, employeeUid } = req.query;

    let query = `SELECT t.*, e.name as employee_name, c.name as component_name 
                 FROM transactions t 
                 LEFT JOIN employees e ON t.employee_uid = e.uid 
                 LEFT JOIN components c ON t.component_uid = c.uid`;
    let params = [];
    let conditions = [];

    if (date) {
        // Match local date string starting with YYYY-MM-DD
        conditions.push(`t.timestamp LIKE ?`);
        params.push(`${date}%`);
    }
    if (employeeUid) {
        conditions.push(`t.employee_uid = ?`);
        params.push(employeeUid);
    }

    if (conditions.length > 0) {
        query += ` WHERE ` + conditions.join(' AND ');
    }

    query += ` ORDER BY t.timestamp DESC LIMIT 200`;

    db.all(query, params, (err, rows) => {
        if (err) return res.status(500).json({ error: err.message });
        res.json({ transactions: rows });
    });
});

// 7b. AUDIT LOGS (RBAC foundation endpoint)
app.get('/api/audit-logs', requireRole('manager'), (req, res) => {
    const limit = Math.min(parseInt(req.query.limit || '100', 10), 500);
    const offset = Math.max(parseInt(req.query.offset || '0', 10), 0);
    const action = req.query.action ? String(req.query.action) : null;

    let query = `SELECT * FROM audit_logs`;
    const params = [];

    if (action) {
        query += ` WHERE action = ?`;
        params.push(action);
    }

    query += ` ORDER BY timestamp DESC LIMIT ? OFFSET ?`;
    params.push(limit, offset);

    db.all(query, params, (err, rows) => {
        if (err) return res.status(500).json({ error: err.message });
        res.json({ logs: rows, limit, offset, count: rows.length });
    });
});

// 8. LOCATION ANALYTICS (Time at location clusters)
app.get('/api/tracking/analytics', (req, res) => {
    const trackerId = req.query.trackerId || 'COMP-ROUTER-001';

    db.all(`SELECT * FROM gps_logs WHERE tracker_id = ? ORDER BY timestamp ASC`, [trackerId], (err, rows) => {
        if (err) return res.status(500).json({ error: err.message });

        // Cluster nearby points (within 50 meters)
        const clusters = [];
        let currentCluster = null;

        rows.forEach((point) => {
            if (!currentCluster) {
                currentCluster = { lat: point.lat, lng: point.lng, startTime: point.timestamp, endTime: point.timestamp, count: 1 };
            } else {
                const dist = haversineDistance(currentCluster.lat, currentCluster.lng, point.lat, point.lng);
                if (dist < 50) {
                    currentCluster.endTime = point.timestamp;
                    currentCluster.count++;
                } else {
                    clusters.push({ ...currentCluster });
                    currentCluster = { lat: point.lat, lng: point.lng, startTime: point.timestamp, endTime: point.timestamp, count: 1 };
                }
            }
        });
        if (currentCluster) clusters.push(currentCluster);

        // Calculate duration for each cluster
        const analytics = clusters.map(c => {
            const start = new Date(c.startTime);
            const end = new Date(c.endTime);
            const durationMin = Math.round((end - start) / 60000);
            const distFromZone = haversineDistance(c.lat, c.lng, geofenceConfig.lat, geofenceConfig.lng);
            return {
                lat: c.lat,
                lng: c.lng,
                duration: durationMin,
                readings: c.count,
                startTime: c.startTime,
                endTime: c.endTime,
                distanceFromZone: Math.round(distFromZone),
                isAuthorized: distFromZone <= geofenceConfig.radius
            };
        });

        res.json({ analytics });
    });
});

// ==========================================
// ADMIN APPROVAL WORKFLOW API
// ==========================================

// Get all requests
app.get('/api/requests', (req, res) => {
    db.all(`SELECT r.*, e.name as employee_name, c.name as component_name 
            FROM requests r
            JOIN employees e ON r.employee_uid = e.uid
            JOIN components c ON r.component_uid = c.uid
            ORDER BY r.timestamp DESC`, [], (err, rows) => {
        if (err) return res.status(500).json({ error: err.message });
        res.json({ requests: rows });
    });
});

// Employee Creates Request
app.post('/api/requests', (req, res) => {
    const { employeeUid, componentUid } = req.body;
    if (!employeeUid || !componentUid) return res.status(400).json({ error: "Missing UIDs" });

    // Check if component is actually IN inventory
    db.get(`SELECT status, name FROM components WHERE uid = ?`, [componentUid], (err, comp) => {
        if (err || !comp) return res.status(404).json({ error: "Component not found" });
        if (comp.status === 'OUT') return res.status(400).json({ error: "Component already out in the field" });

        db.run(`INSERT INTO requests (employee_uid, component_uid, status) VALUES (?, ?, 'pending')`,
            [employeeUid, componentUid], function (err) {
                if (err) return res.status(500).json({ error: err.message });

                // Get Employee name for the email
                db.get(`SELECT name FROM employees WHERE uid = ?`, [employeeUid], (err, emp) => {
                    const empName = emp ? emp.name : employeeUid;
                    const compName = comp.name || componentUid;
                    sendAdminEmail(empName, compName);
                    
                    broadcastUpdate({ type: 'new_request' });
                    res.status(201).json({ message: "Request sent for Admin approval" });
                });
            });
    });
});

// Admin Approves Request
app.post('/api/requests/:id/approve', requireRole('manager'), (req, res) => {
    const reqId = req.params.id;

    db.get(`SELECT * FROM requests WHERE id = ?`, [reqId], (err, request) => {
        if (err || !request) return res.status(404).json({ error: "Request not found" });

        // Update Component to be approved for this employee
        db.run(`UPDATE components SET approved_for_uid = ? WHERE uid = ?`,
            [request.employee_uid, request.component_uid], (err) => {
                if (err) return res.status(500).json({ error: err.message });

                // Update Request Status
                db.run(`UPDATE requests SET status = 'approved' WHERE id = ?`, [reqId], () => {
                    auditFromRequest(req, {
                        action: 'request.approve',
                        entityType: 'request',
                        entityId: String(reqId),
                        details: {
                            employee_uid: request.employee_uid,
                            component_uid: request.component_uid
                        }
                    });
                    broadcastUpdate({ type: 'request_update' });
                    res.json({ message: "Approved successfully. Employee can now check out the item." });
                });
            });
    });
});

// Admin Rejects Request
app.post('/api/requests/:id/reject', requireRole('manager'), (req, res) => {
    db.run(`UPDATE requests SET status = 'rejected' WHERE id = ?`, [req.params.id], (err) => {
        if (err) return res.status(500).json({ error: err.message });
        auditFromRequest(req, {
            action: 'request.reject',
            entityType: 'request',
            entityId: String(req.params.id)
        });
        broadcastUpdate({ type: 'request_update' });
        res.json({ message: "Request rejected." });
    });
});

// START SERVER
const PORT = 3000;
server.listen(PORT, '0.0.0.0', () => {
    console.log(`=========================================`);
    console.log(`Server running on http://localhost:${PORT}`);
    console.log(`Dashboard available at http://localhost:${PORT}/`);
    console.log(`=========================================`);
});
